import { EducationLevel, CurriculumType, ExamCategory } from '@/types/exam';

export interface LevelInfo {
  id: EducationLevel;
  name: string;
  grades: { id: string; name: string; phase?: string }[];
  subjects: string[];
  optionCount: number; // 4 for SD/SMP (A-D), 5 for SMA/SMK (A-E)
}

export const EDUCATION_LEVELS: Record<EducationLevel, LevelInfo> = {
  sd: {
    id: 'sd',
    name: 'SD / MI (Sekolah Dasar)',
    optionCount: 4,
    grades: [
      { id: '1', name: 'Kelas 1', phase: 'Fase A' },
      { id: '2', name: 'Kelas 2', phase: 'Fase A' },
      { id: '3', name: 'Kelas 3', phase: 'Fase B' },
      { id: '4', name: 'Kelas 4', phase: 'Fase B' },
      { id: '5', name: 'Kelas 5', phase: 'Fase C' },
      { id: '6', name: 'Kelas 6', phase: 'Fase C' },
    ],
    subjects: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika',
      'Ilmu Pengetahuan Alam dan Sosial (IPAS)',
      'Pendidikan Agama dan Budi Pekerti',
      'Bahasa Inggris',
      'Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)',
      'Seni Rupa',
      'Seni Musik',
      'Seni Tari',
      'Seni Teater',
      'Bahasa Daerah / Muatan Lokal',
    ],
  },
  smp: {
    id: 'smp',
    name: 'SMP / MTs (Sekolah Menengah Pertama)',
    optionCount: 4,
    grades: [
      { id: '7', name: 'Kelas 7', phase: 'Fase D' },
      { id: '8', name: 'Kelas 8', phase: 'Fase D' },
      { id: '9', name: 'Kelas 9', phase: 'Fase D' },
    ],
    subjects: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika',
      'Ilmu Pengetahuan Alam (IPA)',
      'Ilmu Pengetahuan Sosial (IPS)',
      'Bahasa Inggris',
      'Informatika',
      'Pendidikan Agama dan Budi Pekerti',
      'Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)',
      'Seni dan Prakarya',
      'Bahasa Daerah / Muatan Lokal',
    ],
  },
  sma: {
    id: 'sma',
    name: 'SMA / MA (Sekolah Menengah Atas)',
    optionCount: 5,
    grades: [
      { id: '10', name: 'Kelas 10', phase: 'Fase E' },
      { id: '11', name: 'Kelas 11', phase: 'Fase F' },
      { id: '12', name: 'Kelas 12', phase: 'Fase F' },
    ],
    subjects: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika (Umum)',
      'Matematika Tingkat Lanjut',
      'Bahasa Inggris',
      'Fisika',
      'Kimia',
      'Biologi',
      'Informatika',
      'Sosiologi',
      'Ekonomi',
      'Geografi',
      'Sejarah (Umum)',
      'Antropologi',
      'Pendidikan Agama dan Budi Pekerti',
      'PJOK',
      'Seni Budaya',
    ],
  },
  smk: {
    id: 'smk',
    name: 'SMK / MAK (Sekolah Menengah Kejuruan)',
    optionCount: 5,
    grades: [
      { id: '10', name: 'Kelas 10', phase: 'Fase E' },
      { id: '11', name: 'Kelas 11', phase: 'Fase F' },
      { id: '12', name: 'Kelas 12', phase: 'Fase F' },
    ],
    subjects: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika Terapan',
      'Bahasa Inggris Kejuruan',
      'Informatika',
      'Projek IPAS (SMK)',
      'Produk Kreatif dan Kewirausahaan (PKK)',
      'Dasar-dasar Program Keahlian',
      'Konsentrasi Keahlian Kejuruan',
      'Sejarah',
      'Pendidikan Agama dan Budi Pekerti',
      'PJOK',
      'Seni Budaya',
    ],
  },
};

export const CURRICULUM_SUBJECTS: Record<CurriculumType, Record<EducationLevel, string[]>> = {
  merdeka: {
    sd: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika',
      'Ilmu Pengetahuan Alam dan Sosial (IPAS)',
      'Pendidikan Agama dan Budi Pekerti',
      'Bahasa Inggris',
      'Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)',
      'Seni Rupa',
      'Seni Musik',
      'Seni Tari',
      'Seni Teater',
      'Bahasa Daerah / Muatan Lokal',
    ],
    smp: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika',
      'Ilmu Pengetahuan Alam (IPA)',
      'Ilmu Pengetahuan Sosial (IPS)',
      'Bahasa Inggris',
      'Informatika',
      'Pendidikan Agama dan Budi Pekerti',
      'Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)',
      'Seni dan Prakarya',
      'Bahasa Daerah / Muatan Lokal',
    ],
    sma: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika (Umum)',
      'Matematika Tingkat Lanjut',
      'Bahasa Inggris',
      'Fisika',
      'Kimia',
      'Biologi',
      'Informatika',
      'Sosiologi',
      'Ekonomi',
      'Geografi',
      'Sejarah (Umum)',
      'Antropologi',
      'Pendidikan Agama dan Budi Pekerti',
      'PJOK',
      'Seni Budaya',
      'Bahasa & Sastra Indonesia',
      'Bahasa & Sastra Inggris',
    ],
    smk: [
      'Pendidikan Pancasila',
      'Bahasa Indonesia',
      'Matematika Terapan',
      'Bahasa Inggris Kejuruan',
      'Informatika',
      'Projek IPAS (SMK)',
      'Produk Kreatif dan Kewirausahaan (PKK)',
      'Dasar-dasar Program Keahlian',
      'Konsentrasi Keahlian Kejuruan',
      'Sejarah',
      'Pendidikan Agama dan Budi Pekerti',
      'PJOK',
      'Seni Budaya',
    ],
  },
  k13: {
    sd: [
      'Tematik Terpadu',
      'Pendidikan Agama dan Budi Pekerti',
      'PPKn (Pendidikan Pancasila dan Kewarganegaraan)',
      'Bahasa Indonesia',
      'Matematika',
      'Ilmu Pengetahuan Alam (IPA)',
      'Ilmu Pengetahuan Sosial (IPS)',
      'Seni Budaya dan Prakarya (SBdP)',
      'Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)',
      'Bahasa Inggris (Muatan Lokal)',
      'Bahasa Daerah / Muatan Lokal',
    ],
    smp: [
      'Pendidikan Agama dan Budi Pekerti',
      'PPKn (Pendidikan Pancasila dan Kewarganegaraan)',
      'Bahasa Indonesia',
      'Matematika',
      'Ilmu Pengetahuan Alam (IPA)',
      'Ilmu Pengetahuan Sosial (IPS)',
      'Bahasa Inggris',
      'Seni Budaya',
      'Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)',
      'Prakarya',
      'Informatika / Bimbingan TIK',
      'Bahasa Daerah / Muatan Lokal',
    ],
    sma: [
      'Pendidikan Agama dan Budi Pekerti',
      'PPKn (Pendidikan Pancasila dan Kewarganegaraan)',
      'Bahasa Indonesia',
      'Matematika (Wajib)',
      'Matematika (Peminatan MIPA)',
      'Bahasa Inggris (Wajib)',
      'Sejarah Indonesia (Wajib)',
      'Fisika',
      'Kimia',
      'Biologi',
      'Ekonomi',
      'Sosiologi',
      'Geografi',
      'Sejarah (Peminatan IPS)',
      'Antropologi',
      'Bahasa & Sastra Indonesia (Peminatan)',
      'Bahasa & Sastra Inggris (Peminatan)',
      'Seni Budaya',
      'PJOK',
      'Prakarya dan Kewirausahaan (PKWU)',
    ],
    smk: [
      'Pendidikan Agama dan Budi Pekerti',
      'PPKn (Pendidikan Pancasila dan Kewarganegaraan)',
      'Bahasa Indonesia',
      'Matematika (Kejuruan)',
      'Bahasa Inggris & Bahasa Asing',
      'Sejarah Indonesia',
      'Seni Budaya',
      'PJOK',
      'Simulasi dan Komunikasi Digital (Simdig)',
      'Fisika Terapan',
      'Kimia Terapan',
      'IPA Terapan',
      'Dasar Bidang Keahlian',
      'Dasar Program Keahlian',
      'Kompetensi Keahlian Kejuruan',
      'Produk Kreatif dan Kewirausahaan (PKK)',
    ],
  },
};

export function getSubjectsForLevel(level: EducationLevel, curriculum: CurriculumType = 'merdeka'): string[] {
  return CURRICULUM_SUBJECTS[curriculum]?.[level] || EDUCATION_LEVELS[level]?.subjects || [];
}

export const EXAM_CATEGORIES: { id: ExamCategory; label: string; defaultTitle: string; defaultDuration: number }[] = [
  {
    id: 'formatif',
    label: 'Ulangan Harian / Asesmen Formatif',
    defaultTitle: 'ASESMEN FORMATIF / ULANGAN HARIAN',
    defaultDuration: 45,
  },
  {
    id: 'sts',
    label: 'STS / PTS (Tengah Semester)',
    defaultTitle: 'SUMATIF TENGAH SEMESTER (STS)',
    defaultDuration: 60,
  },
  {
    id: 'sas',
    label: 'SAS / PAS (Akhir Semester)',
    defaultTitle: 'SUMATIF AKHIR SEMESTER (SAS)',
    defaultDuration: 90,
  },
  {
    id: 'us',
    label: 'Ujian Sekolah / Asesmen Akhir',
    defaultTitle: 'UJIAN SEKOLAH (US) / ASESMEN AKHIR JENJANG',
    defaultDuration: 120,
  },
];

export const CURRICULA: { id: CurriculumType; label: string }[] = [
  { id: 'merdeka', label: 'Kurikulum Merdeka (Capaian & Tujuan Pembelajaran)' },
  { id: 'k13', label: 'Kurikulum 2013 / K-13 (Kompetensi Dasar)' },
];

import { AIProviderConfig, UserAISettings } from '@/types/exam';

export const AI_PROVIDERS: AIProviderConfig[] = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    tagline: 'Pilihan Utama Guru Indonesia - Gratis & Cerdas',
    tierBadge: '🟢 Gratis (Rekomendasi)',
    tierType: 'free',
    description: 'Gratis 100% menggunakan akun Google / Gmail via Google AI Studio (hingga 15 request/menit).',
    defaultModel: 'gemini-3.6-flash',
    availableModels: [
      { id: 'gemini-3.6-flash', name: 'Gemini 3.6 Flash', badge: 'Versi Terbaru (Rekomendasi)', description: 'Model Gemini versi 3.6 Google yang super cepat, cerdas, dan efisien' },
      { id: 'gemini-3.7-flash', name: 'Gemini 3.7 Flash', badge: 'Terbaru / Flagship', description: 'Model generasi Gemini 3.7 dengan penalaran tinggi' },
      { id: 'custom', name: 'Model Custom Gemini Lainnya...', badge: 'Custom', description: 'Gunakan nama model Gemini lainnya di Google AI Studio' },
    ],
    requiresApiKey: true,
    apiKeyPlaceholder: 'AIzaSy...',
    apiKeyHelpTitle: 'Cara Mendapatkan Gemini API Key Gratis:',
    apiKeyHelpUrl: 'https://aistudio.google.com/app/apikey',
    apiKeyHelpSteps: [
      'Buka Google AI Studio (aistudio.google.com/app/apikey)',
      'Login dengan akun Google/Gmail Anda',
      'Klik tombol "Create API Key"',
      'Salin dan tempelkan key di form ini',
    ],
  },
  {
    id: 'groq',
    name: 'Groq Cloud',
    tagline: 'Generasi Super Kilat (300+ Token/Detik)',
    tierBadge: '⚡ Gratis (Super Cepat)',
    tierType: 'free',
    description: 'Layanan inferensi AI tercepat di dunia dengan kuota gratis harian besar. Menjalankan model Llama 3.3 & DeepSeek R1.',
    defaultModel: 'llama-3.3-70b-versatile',
    availableModels: [
      { id: 'llama-3.3-70b-versatile', name: 'Meta Llama 3.3 70B', badge: 'Rekomendasi', description: 'Model flagship Meta terbaru setara Llama 3.1 405B, pemahaman bahasa sangat akurat' },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill Llama 70B', badge: 'Penalaran / HOTS', description: 'Model reasoning kuat berkecepatan 300+ token/detik di Groq' },
      { id: 'deepseek-r1-distill-qwen-32b', name: 'DeepSeek R1 Distill Qwen 32B', badge: 'Penalaran Presisi', description: 'Penalaran logika & matematika presisi tinggi' },
      { id: 'llama-3.1-8b-instant', name: 'Meta Llama 3.1 8B', badge: 'Super Kilat', description: 'Generasi instan dalam hitungan detik' },
      { id: 'gemma2-9b-it', name: 'Google Gemma 2 9B', badge: 'Google di Groq', description: 'Model Google Gemma 2 berkecepatan tinggi di Groq' },
    ],
    requiresApiKey: true,
    apiKeyPlaceholder: 'gsk_...',
    apiKeyHelpTitle: 'Cara Mendapatkan Groq API Key Gratis:',
    apiKeyHelpUrl: 'https://console.groq.com/keys',
    apiKeyHelpSteps: [
      'Buka Groq Console (console.groq.com/keys)',
      'Daftar / Login dengan akun Google atau GitHub',
      'Klik menu "API Keys" lalu klik "Create API Key"',
      'Beri nama lalu salin key yang diawali gsk_...',
    ],
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    tagline: 'Akses Banyak Model AI Gratis dengan 1 API Key',
    tierBadge: '🌐 Gratis Multi-Model',
    tierType: 'freemium',
    description: 'Hub model AI internasional. Menyediakan banyak pilihan model bertanda ":free" tanpa perlu kartu kredit.',
    defaultModel: 'deepseek/deepseek-chat:free',
    availableModels: [
      { id: 'deepseek/deepseek-chat:free', name: 'DeepSeek V3 (Free)', badge: 'Gratis / Cerdas', description: 'Model general flagship DeepSeek V3 671B gratis' },
      { id: 'deepseek/deepseek-r1:free', name: 'DeepSeek R1 (Free)', badge: 'Gratis / HOTS', description: 'Model penalaran mendalam tercanggih DeepSeek tanpa biaya' },
      { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B Instruct (Free)', badge: 'Gratis', description: 'Model open-source tercerdas dari Meta' },
      { id: 'qwen/qwen-2.5-72b-instruct:free', name: 'Qwen 2.5 72B Instruct (Free)', badge: 'Gratis', description: 'Multibahasa & Bahasa Indonesia luar biasa' },
      { id: 'mistralai/mistral-small-24b-instruct-2501:free', name: 'Mistral Small 24B (Free)', badge: 'Gratis', description: 'Model efisien terbaru dari Mistral AI' },
      { id: 'custom', name: 'Model OpenRouter Lainnya...', badge: 'Custom', description: 'Gunakan ID model lain dari katalog OpenRouter' },
    ],
    requiresApiKey: true,
    apiKeyPlaceholder: 'sk-or-v1-...',
    apiKeyHelpTitle: 'Cara Mendapatkan OpenRouter API Key Gratis:',
    apiKeyHelpUrl: 'https://openrouter.ai/keys',
    apiKeyHelpSteps: [
      'Buka OpenRouter (openrouter.ai/keys)',
      'Login / Sign Up akun baru',
      'Klik "Create Key", beri nama dan biarkan credit limit kosong/default',
      'Salin key dan gunakan untuk model-model gratis (:free)',
    ],
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek Official API',
    tagline: 'Model Penalaran Terbaik dengan Biaya Termurah',
    tierBadge: '💳 Berbayar (Sangat Murah)',
    tierType: 'paid',
    description: 'API resmi DeepSeek. Sangat murah dan luar biasa cerdas dalam pembuatan soal HOTS dan sains.',
    defaultModel: 'deepseek-chat',
    availableModels: [
      { id: 'deepseek-chat', name: 'DeepSeek-V3 (Chat)', badge: 'Rekomendasi V3', description: 'Model general flagship DeepSeek V3 (671B) sangat cerdas & murah' },
      { id: 'deepseek-reasoner', name: 'DeepSeek-R1 (Reasoning)', badge: 'HOTS & Sains Tertinggi', description: 'Berpikir mendalam (Chain-of-Thought) untuk soal matematika, fisika, & analisis' },
    ],
    requiresApiKey: true,
    apiKeyPlaceholder: 'sk-...',
    apiKeyHelpTitle: 'Cara Mendapatkan DeepSeek API Key:',
    apiKeyHelpUrl: 'https://platform.deepseek.com/api_keys',
    apiKeyHelpSteps: [
      'Buka platform.deepseek.com',
      'Daftar dan lakukan top-up saldo minimum (sekitar $2)',
      'Buka menu API Keys dan buat key baru',
    ],
    defaultBaseUrl: 'https://api.deepseek.com/v1',
  },
  {
    id: 'openai',
    name: 'OpenAI (ChatGPT)',
    tagline: 'Standar Industri GPT-4o & Model Reasoning o3-mini',
    tierBadge: '💳 Berbayar',
    tierType: 'paid',
    description: 'Model standar industri dari OpenAI dengan format JSON yang sangat stabil dan terpercaya.',
    defaultModel: 'gpt-4o-mini',
    availableModels: [
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', badge: 'Rekomendasi Hemat', description: 'Cepat, hemat biaya, dan sangat akurat untuk pembuatan soal' },
      { id: 'gpt-4o', name: 'GPT-4o (Omni Flagship)', badge: 'Kualitas Tertinggi', description: 'Model flagship OpenAI untuk naskah ujian terlengkap' },
      { id: 'o3-mini', name: 'OpenAI o3-mini', badge: 'Reasoning Terbaru', description: 'Model penalaran STEM & logika terbaru OpenAI berkecepatan tinggi' },
      { id: 'o1', name: 'OpenAI o1', badge: 'Penalaran Mendalam', description: 'Model penalaran tingkat tinggi untuk soal ujian HOTS kompleks' },
      { id: 'gpt-4.5-preview', name: 'GPT-4.5 Preview', badge: 'Flagship Terbesar', description: 'Model terbesar OpenAI dengan wawasan pengetahuan luas' },
    ],
    requiresApiKey: true,
    apiKeyPlaceholder: 'sk-proj-...',
    apiKeyHelpTitle: 'Cara Mendapatkan OpenAI API Key:',
    apiKeyHelpUrl: 'https://platform.openai.com/api-keys',
    apiKeyHelpSteps: [
      'Buka platform.openai.com/api-keys',
      'Login dan pastikan akun memiliki saldo API kredit',
      'Klik "Create new secret key" dan tempelkan di sini',
    ],
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    tagline: 'Kecerdasan Tata Bahasa & Penalaran Hybrid Claude 3.7',
    tierBadge: '💳 Berbayar',
    tierType: 'paid',
    description: 'Model AI tercanggih dari Anthropic dengan pemahaman kurikulum dan tata Bahasa Indonesia yang sangat natural.',
    defaultModel: 'claude-3-7-sonnet-20250219',
    availableModels: [
      { id: 'claude-3-7-sonnet-20250219', name: 'Claude 3.7 Sonnet', badge: 'Terbaru / Hybrid', description: 'Model hybrid reasoning pertama di dunia dari Anthropic' },
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet v2', badge: 'Standar Industri', description: 'Kualitas tata bahasa & instruksi terbaik di kelasnya' },
      { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku', badge: 'Super Kilat & Hemat', description: 'Cepat dan efisien dengan kecerdasan setara Opus 3' },
    ],
    requiresApiKey: true,
    apiKeyPlaceholder: 'sk-ant-api03-...',
    apiKeyHelpTitle: 'Cara Mendapatkan Anthropic API Key:',
    apiKeyHelpUrl: 'https://console.anthropic.com/settings/keys',
    apiKeyHelpSteps: [
      'Buka Anthropic Console (console.anthropic.com/settings/keys)',
      'Login atau buat akun Anthropic Anda',
      'Buka menu "API Keys" lalu klik "Create Key"',
      'Salin key yang berawalan sk-ant-... dan tempelkan di sini',
    ],
    defaultBaseUrl: 'https://api.anthropic.com/v1',
  },
  {
    id: 'ollama',
    name: 'Ollama (Lokal / Offline)',
    tagline: '100% Offline, Gratis, & Privasi Aman di Komputer Anda',
    tierBadge: '💻 Lokal / Offline',
    tierType: 'local',
    description: 'Jalankan AI langsung di komputer/laptop Anda tanpa koneksi internet dan tanpa perlu API Key.',
    defaultModel: 'qwen2.5:7b',
    availableModels: [
      { id: 'qwen2.5:7b', name: 'Qwen 2.5 (7B)', badge: 'Rekomendasi Lokal', description: 'Bahasa Indonesia sangat fasih (RAM ~8GB)' },
      { id: 'qwen2.5:14b', name: 'Qwen 2.5 (14B)', badge: 'Akurasi Tinggi', description: 'Kualitas naskah sangat baik untuk PC dengan GPU/RAM 16GB+' },
      { id: 'deepseek-r1:8b', name: 'DeepSeek R1 (8B)', badge: 'Penalaran Lokal', description: 'Model reasoning lokal untuk soal numerasi & sains' },
      { id: 'deepseek-r1:14b', name: 'DeepSeek R1 (14B)', badge: 'Penalaran Kuat', description: 'Penalaran logika lebih mendalam berbasis Qwen 14B' },
      { id: 'llama3.3:70b', name: 'Llama 3.3 (70B)', badge: 'Flagship Lokal', description: 'Model lokal kapasitas besar untuk server/workstation' },
      { id: 'llama3.2:3b', name: 'Llama 3.2 (3B)', badge: 'Sangat Ringan', description: 'Sangat hemat RAM untuk laptop biasa (RAM ~4GB)' },
      { id: 'mistral:latest', name: 'Mistral (7B)', badge: 'Populer', description: 'Model open source populer untuk naskah umum' },
      { id: 'custom', name: 'Model Custom Lainnya...', badge: 'Custom', description: 'Gunakan nama model apapun yang sudah di-pull di Ollama' },
    ],
    requiresApiKey: false,
    supportsCustomBaseUrl: true,
    defaultBaseUrl: 'http://localhost:11434/v1',
    apiKeyHelpTitle: 'Panduan Menjalankan Ollama Lokal:',
    apiKeyHelpUrl: 'https://ollama.com',
    apiKeyHelpSteps: [
      'Download & instal Ollama dari ollama.com di laptop/PC Anda',
      'Buka Command Prompt / Terminal, jalankan: ollama run qwen2.5:7b',
      'Pastikan Ollama berjalan di background (port 11434)',
      'Aplikasi ini akan otomatis terhubung ke localhost Anda tanpa internet!',
    ],
  },
];

export const DEFAULT_AI_SETTINGS: UserAISettings = {
  activeProvider: 'gemini',
  providers: {
    gemini: {
      apiKey: '',
      model: 'gemini-3.6-flash',
    },
    groq: {
      apiKey: '',
      model: 'llama-3.3-70b-versatile',
      customBaseUrl: 'https://api.groq.com/openai/v1',
    },
    openrouter: {
      apiKey: '',
      model: 'deepseek/deepseek-chat:free',
      customBaseUrl: 'https://openrouter.ai/api/v1',
    },
    deepseek: {
      apiKey: '',
      model: 'deepseek-chat',
      customBaseUrl: 'https://api.deepseek.com/v1',
    },
    openai: {
      apiKey: '',
      model: 'gpt-4o-mini',
      customBaseUrl: 'https://api.openai.com/v1',
    },
    anthropic: {
      apiKey: '',
      model: 'claude-3-7-sonnet-20250219',
      customBaseUrl: 'https://api.anthropic.com/v1',
    },
    ollama: {
      apiKey: 'ollama',
      model: 'qwen2.5:7b',
      customBaseUrl: 'http://localhost:11434/v1',
    },
  },
};

